In [17]:
import pandas as pd 
import numpy as np 
import torch 
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import accuracy_score
import torch.nn as nn
import torch.optim as optim

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [6]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=23,shuffle=True)

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
X_train

array([[-0.64412895,  0.46219725, -0.65608071, ..., -0.66179182,
        -0.71957181,  0.04384952],
       [ 2.35563493,  0.04279733,  2.55151997, ...,  2.67422922,
         1.78101465,  0.71319128],
       [-1.30065367, -0.22327359, -1.28860089, ..., -0.76666742,
         0.41860484,  0.03473189],
       ...,
       [-0.67023908, -0.17592199, -0.5972025 , ...,  0.59198299,
         2.87279822,  2.98241003],
       [-0.71665709, -0.74639608, -0.6998188 , ..., -0.26976775,
        -0.15357636, -0.23343388],
       [-0.20605898,  0.47347144, -0.25024163, ..., -0.07054991,
         0.14024642, -0.70433297]], shape=(455, 30))

In [9]:
label=LabelEncoder()
y_train=label.fit_transform(y_train)
y_test=label.transform(y_test)

In [10]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1])

In [39]:
X_train_ten=torch.tensor(X_train,requires_grad=True,dtype=torch.float32)
X_test_ten=torch.tensor(X_test,requires_grad=True,dtype=torch.float32)
y_train_ten=torch.tensor(y_train,dtype=torch.float32)
y_test_ten=torch.tensor(y_test,dtype=torch.float32)

In [12]:
X_train_ten.dtype

torch.float64

In [13]:
X_train_ten

tensor([[-0.6441,  0.4622, -0.6561,  ..., -0.6618, -0.7196,  0.0438],
        [ 2.3556,  0.0428,  2.5515,  ...,  2.6742,  1.7810,  0.7132],
        [-1.3007, -0.2233, -1.2886,  ..., -0.7667,  0.4186,  0.0347],
        ...,
        [-0.6702, -0.1759, -0.5972,  ...,  0.5920,  2.8728,  2.9824],
        [-0.7167, -0.7464, -0.6998,  ..., -0.2698, -0.1536, -0.2334],
        [-0.2061,  0.4735, -0.2502,  ..., -0.0705,  0.1402, -0.7043]],
       dtype=torch.float64, requires_grad=True)

In [40]:
class MyNeuralNetwork(nn.Module):
 
    def __init__(self,feature_size):
        super().__init__()
        self.linear=nn.Linear(feature_size,1)
        self.sigmoid=nn.Sigmoid()
 
    def forward(self,X): 
        out=self.linear(X)
        out=self.sigmoid(out)
        return out
        
        
    def loss(self,y_pred,y): 
        bce=nn.BCELoss()
        los=bce(y_pred,y)
        return los
    
    def backpropagation(self,loss): 
        loss.backward()

In [42]:
model=MyNeuralNetwork(X_train_ten.shape[1])

In [43]:
lr=0.001
epochs=75

In [44]:
model.linear.weight

Parameter containing:
tensor([[-0.0867, -0.0516,  0.1271,  0.0023, -0.1059,  0.0881, -0.1189,  0.0662,
          0.1201,  0.0015,  0.0535,  0.1218,  0.0884,  0.0383,  0.0106, -0.0315,
          0.0499,  0.1112,  0.0014,  0.0784,  0.1064,  0.0529,  0.0216,  0.0698,
          0.1395, -0.1188, -0.1668,  0.1079,  0.0894,  0.1439]],
       requires_grad=True)

In [45]:
model.linear.bias

Parameter containing:
tensor([0.0977], requires_grad=True)

In [46]:
optimizer=optim.Adam(model.parameters(),lr=lr)
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)

In [47]:
for epoch in range(epochs): 
    y_pred=model(X_train_ten) 
    loss=model.loss(y_pred,y_train_ten.reshape(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f'Loss for Epoch {epoch+1} Loss {loss}')

Loss for Epoch 1 Loss 0.5451687574386597
Loss for Epoch 2 Loss 0.5402334928512573
Loss for Epoch 3 Loss 0.5353586077690125
Loss for Epoch 4 Loss 0.5305445790290833
Loss for Epoch 5 Loss 0.5257918238639832
Loss for Epoch 6 Loss 0.5211005806922913
Loss for Epoch 7 Loss 0.5164713263511658
Loss for Epoch 8 Loss 0.5119040608406067
Loss for Epoch 9 Loss 0.5073990821838379
Loss for Epoch 10 Loss 0.5029563903808594
Loss for Epoch 11 Loss 0.4985760748386383
Loss for Epoch 12 Loss 0.49425798654556274
Loss for Epoch 13 Loss 0.4900020956993103
Loss for Epoch 14 Loss 0.48580822348594666
Loss for Epoch 15 Loss 0.4816761016845703
Loss for Epoch 16 Loss 0.4776054918766022
Loss for Epoch 17 Loss 0.47359606623649597
Loss for Epoch 18 Loss 0.4696473777294159
Loss for Epoch 19 Loss 0.4657590985298157
Loss for Epoch 20 Loss 0.46193063259124756
Loss for Epoch 21 Loss 0.45816150307655334
Loss for Epoch 22 Loss 0.45445117354393005
Loss for Epoch 23 Loss 0.450798898935318
Loss for Epoch 24 Loss 0.4472041428089142
Loss for Epoch 25 Loss 0.4436662495136261
Loss for Epoch 26 Loss 0.44018444418907166
Loss for Epoch 27 Loss 0.43675801157951355
Loss for Epoch 28 Loss 0.4333861768245697
Loss for Epoch 29 Loss 0.43006816506385803
Loss for Epoch 30 Loss 0.4268032908439636
Loss for Epoch 31 Loss 0.4235904812812805
Loss for Epoch 32 Loss 0.4204291105270386
Loss for Epoch 33 Loss 0.4173182249069214
Loss for Epoch 34 Loss 0.4142570197582245
Loss for Epoch 35 Loss 0.4112446904182434
Loss for Epoch 36 Loss 0.40828028321266174
Loss for Epoch 37 Loss 0.40536296367645264
Loss for Epoch 38 Loss 0.40249183773994446
Loss for Epoch 39 Loss 0.39966604113578796
Loss for Epoch 40 Loss 0.3968847990036011
Loss for Epoch 41 Loss 0.394147127866745
Loss for Epoch 42 Loss 0.39145225286483765
Loss for Epoch 43 Loss 0.388799250125885
Loss for Epoch 44 Loss 0.386187344789505
Loss for Epoch 45 Loss 0.383615642786026
Loss for Epoch 46 Loss 0.3810834288597107
Loss for Epoch 47 Loss 0.37858977913856506
Loss for Epoch 48 Loss 0.3761339485645294
Loss for Epoch 49 Loss 0.3737150728702545
Loss for Epoch 50 Loss 0.3713324964046478
Loss for Epoch 51 Loss 0.3689853250980377
Loss for Epoch 52 Loss 0.36667296290397644
Loss for Epoch 53 Loss 0.36439451575279236
Loss for Epoch 54 Loss 0.3621493875980377
Loss for Epoch 55 Loss 0.35993683338165283
Loss for Epoch 56 Loss 0.3577560484409332
Loss for Epoch 57 Loss 0.3556065857410431
Loss for Epoch 58 Loss 0.3534875214099884
Loss for Epoch 59 Loss 0.35139837861061096
Loss for Epoch 60 Loss 0.34933850169181824
Loss for Epoch 61 Loss 0.3473072052001953
Loss for Epoch 62 Loss 0.3453039824962616
Loss for Epoch 63 Loss 0.3433281183242798
Loss for Epoch 64 Loss 0.34137916564941406
Loss for Epoch 65 Loss 0.3394564688205719
Loss for Epoch 66 Loss 0.3375595211982727
Loss for Epoch 67 Loss 0.3356877863407135
Loss for Epoch 68 Loss 0.3338407874107361
Loss for Epoch 69 Loss 0.3320178687572479
Loss for Epoch 70 Loss 0.33021870255470276
Loss for Epoch 71 Loss 0.3284427225589752
Loss for Epoch 72 Loss 0.3266894519329071
Loss for Epoch 73 Loss 0.3249585032463074
Loss for Epoch 74 Loss 0.3232493996620178
Loss for Epoch 75 Loss 0.32156169414520264

In [52]:
X_test_ten.shape

torch.Size([114, 30])

In [62]:
model.linear.weight.reshape(-1,1).shape

torch.Size([30, 1])

In [63]:
y_pred_test = torch.sigmoid(X_test_ten @ model.linear.weight.reshape(-1,1) + model.linear.bias)
y_pred_test

tensor([[0.2961],
        [0.5740],
        [0.9731],
        [0.3933],
        [0.7476],
        [0.9189],
        [0.8810],
        [0.3370],
        [0.2263],
        [0.7538],
        [0.9996],
        [0.1001],
        [0.1935],
        [0.2651],
        [0.3305],
        [0.1536],
        [0.1728],
        [0.5771],
        [0.8819],
        [0.3530],
        [0.2213],
        [0.2335],
        [0.8470],
        [0.1972],
        [0.5443],
        [0.4036],
        [0.3096],
        [0.2773],
        [0.2426],
        [0.4564],
        [0.3516],
        [0.8590],
        [0.9821],
        [0.2646],
        [0.2471],
        [0.2889],
        [0.1602],
        [0.2491],
        [0.3007],
        [0.1108],
        [0.3400],
        [0.1019],
        [0.0654],
        [0.5026],
        [0.4753],
        [0.2873],
        [0.2844],
        [0.3269],
        [0.2177],
        [0.3306],
        [0.6819],
        [0.2082],
        [0.8508],
        [0.3313],
        [0.7492],
        [0.8965],
        [0.4183],
        [0.9815],
        [0.3368],
        [0.5749],
        [0.3052],
        [0.7584],
        [0.8410],
        [0.1049],
        [0.4291],
        [0.3227],
        [0.3269],
        [0.1507],
        [0.2241],
        [0.9089],
        [0.5990],
        [0.9709],
        [0.4576],
        [0.2046],
        [0.4317],
        [0.2193],
        [0.6861],
        [0.1491],
        [0.2015],
        [0.3486],
        [0.1942],
        [0.8436],
        [0.2489],
        [0.3437],
        [0.1506],
        [0.6265],
        [0.2962],
        [0.8914],
        [0.4856],
        [0.9465],
        [0.9510],
        [0.5966],
        [0.6075],
        [0.4647],
        [0.1413],
        [0.9711],
        [0.7221],
        [0.1993],
        [0.1000],
        [0.7918],
        [0.7649],
        [0.2500],
        [0.4479],
        [0.1758],
        [0.2470],
        [0.8416],
        [0.2639],
        [0.0782],
        [0.3177],
        [0.9608],
        [0.1881],
        [0.4224],
        [0.1801],
        [0.8065]], grad_fn=<SigmoidBackward0>)

In [64]:
y_pred_test.shape

torch.Size([114, 1])

In [65]:
y_pred_class = (y_pred_test >= 0.5).double()
y_pred_class

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.]], dtype=torch.float64)

In [66]:
accuracy_score(
    y_test_ten.detach().numpy(),
    y_pred_class.detach().numpy()
)

0.956140350877193