In [143]:
import pandas as pd 
import numpy as np 
import torch 
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import accuracy_score

In [100]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [101]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [102]:
df.shape

(569, 33)

In [103]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [104]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=23,shuffle=True)

In [105]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [106]:
X_train

array([[-0.64412895,  0.46219725, -0.65608071, ..., -0.66179182,
        -0.71957181,  0.04384952],
       [ 2.35563493,  0.04279733,  2.55151997, ...,  2.67422922,
         1.78101465,  0.71319128],
       [-1.30065367, -0.22327359, -1.28860089, ..., -0.76666742,
         0.41860484,  0.03473189],
       ...,
       [-0.67023908, -0.17592199, -0.5972025 , ...,  0.59198299,
         2.87279822,  2.98241003],
       [-0.71665709, -0.74639608, -0.6998188 , ..., -0.26976775,
        -0.15357636, -0.23343388],
       [-0.20605898,  0.47347144, -0.25024163, ..., -0.07054991,
         0.14024642, -0.70433297]], shape=(455, 30))

In [107]:
label=LabelEncoder()
y_train=label.fit_transform(y_train)
y_test=label.transform(y_test)

In [108]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1])

In [109]:
X_train_ten=torch.tensor(X_train,requires_grad=True)
X_test_ten=torch.tensor(X_test,requires_grad=True)
y_train_ten=torch.tensor(y_train,dtype=torch.float64)
y_test_ten=torch.tensor(y_test,dtype=torch.float64)

In [110]:
X_train_ten.dtype

torch.float64

In [111]:
X_train_ten

tensor([[-0.6441,  0.4622, -0.6561,  ..., -0.6618, -0.7196,  0.0438],
        [ 2.3556,  0.0428,  2.5515,  ...,  2.6742,  1.7810,  0.7132],
        [-1.3007, -0.2233, -1.2886,  ..., -0.7667,  0.4186,  0.0347],
        ...,
        [-0.6702, -0.1759, -0.5972,  ...,  0.5920,  2.8728,  2.9824],
        [-0.7167, -0.7464, -0.6998,  ..., -0.2698, -0.1536, -0.2334],
        [-0.2061,  0.4735, -0.2502,  ..., -0.0705,  0.1402, -0.7043]],
       dtype=torch.float64, requires_grad=True)

In [112]:
class MyNeuralNetwork():
    np.random.seed(42)
    def __init__(self,X): 
        self.weights=torch.rand(X.shape[1],1,requires_grad=True,dtype=torch.float64)
        self.bias=torch.zeros(1,requires_grad=True,dtype=torch.float64) 

    def forward(self,X): 
        z=torch.matmul(X,self.weights) + self.bias
        y_pred=torch.sigmoid(z)
        return y_pred 

    def loss(self,y_pred,y): 
        bce=nn.BCELoss()
        los=bce(y_pred,y)
        return los
    
    def backpropagation(self,loss): 
        loss.backward()

    def update_weights(self): 
        with torch.no_grad():
            self.weights-=lr*self.weights.grad
            self.bias-=lr*self.bias.grad
        self.weights.grad.zero_()
        self.bias.grad.zero_()

In [113]:
model=MyNeuralNetwork(X_train_ten)
model.weights

tensor([[0.6288],
        [0.4842],
        [0.9903],
        [0.9223],
        [0.1620],
        [0.5165],
        [0.2368],
        [0.2523],
        [0.9546],
        [0.0108],
        [0.6710],
        [0.1315],
        [0.7421],
        [0.3444],
        [0.6141],
        [0.7652],
        [0.4688],
        [0.5259],
        [0.8359],
        [0.7841],
        [0.0475],
        [0.8151],
        [0.0678],
        [0.5548],
        [0.2811],
        [0.2112],
        [0.1853],
        [0.8233],
        [0.0394],
        [0.8168]], dtype=torch.float64, requires_grad=True)

In [114]:
model.weights.shape

torch.Size([30, 1])

In [115]:
X_train_ten.shape

torch.Size([455, 30])

In [126]:
lr=0.01
epochs=1000

In [117]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
for epoch in range(epochs): 
    y_pred=model.forward(X_train_ten)
    loss=model.loss(y_pred,y_train_ten.reshape(-1,1))
    print(f'Loss for Epoch {epoch+1} Loss {loss}')
    model.backpropagation(loss) 
    model.update_weights()

In [119]:
y_pred.shape

torch.Size([455, 1])

In [120]:
y_train_ten.shape

torch.Size([455])

In [121]:
y_train_ten.dtype

torch.float64

In [128]:
model.weights

tensor([[ 0.7657],
        [ 0.5705],
        [ 1.1025],
        [ 1.0592],
        [ 0.1149],
        [ 0.1482],
        [ 0.0893],
        [ 0.2570],
        [ 0.5830],
        [-0.4997],
        [ 0.6446],
        [-0.2110],
        [ 0.6607],
        [ 0.3995],
        [ 0.2116],
        [-0.0606],
        [-0.1913],
        [-0.0992],
        [ 0.2842],
        [-0.1362],
        [ 0.2950],
        [ 1.1120],
        [ 0.2758],
        [ 0.7832],
        [ 0.5733],
        [ 0.0868],
        [ 0.1891],
        [ 0.9573],
        [ 0.1464],
        [ 0.6111]], dtype=torch.float64, requires_grad=True)

In [129]:
model.bias

tensor([-0.1378], dtype=torch.float64, requires_grad=True)

In [131]:
X_test_ten.shape

torch.Size([114, 30])

In [132]:
model.weights.shape

torch.Size([30, 1])

In [146]:
y_pred_test = torch.sigmoid(X_test_ten @ model.weights + model.bias)
y_pred_test

tensor([[7.4368e-03],
        [8.8014e-01],
        [1.0000e+00],
        [3.6269e-02],
        [9.8063e-01],
        [1.0000e+00],
        [9.9997e-01],
        [9.9730e-02],
        [2.8093e-03],
        [9.9891e-01],
        [1.0000e+00],
        [3.1545e-04],
        [4.5881e-04],
        [1.0704e-04],
        [3.6633e-03],
        [1.5542e-04],
        [6.6673e-04],
        [9.3694e-02],
        [9.9998e-01],
        [3.1754e-02],
        [1.7594e-02],
        [6.9369e-03],
        [9.9976e-01],
        [1.2284e-03],
        [7.3145e-01],
        [5.2920e-02],
        [3.2657e-03],
        [5.1639e-03],
        [1.9916e-02],
        [1.1649e-01],
        [4.0486e-02],
        [9.9315e-01],
        [1.0000e+00],
        [2.1219e-03],
        [4.1666e-03],
        [9.4244e-03],
        [2.3687e-05],
        [6.2416e-03],
        [7.0255e-02],
        [1.4911e-05],
        [1.6984e-02],
        [9.1516e-06],
        [4.0835e-06],
        [7.5583e-01],
        [6.6441e-01],
        [7.4196e-04],
        [4.1905e-03],
        [2.5889e-04],
        [2.0879e-03],
        [3.0781e-02],
        [9.6696e-01],
        [1.8351e-03],
        [9.9874e-01],
        [6.5375e-03],
        [9.9686e-01],
        [9.9997e-01],
        [9.2718e-04],
        [1.0000e+00],
        [1.4143e-02],
        [2.7980e-03],
        [1.0102e-03],
        [9.9565e-01],
        [9.9952e-01],
        [5.7090e-04],
        [8.5888e-02],
        [7.8860e-02],
        [8.0489e-03],
        [3.8595e-04],
        [3.3810e-03],
        [1.0000e+00],
        [9.5948e-01],
        [1.0000e+00],
        [1.9922e-01],
        [2.7644e-04],
        [4.4941e-03],
        [9.0401e-04],
        [9.8209e-01],
        [1.0731e-04],
        [2.5451e-04],
        [4.1622e-03],
        [1.1506e-03],
        [9.9997e-01],
        [1.4276e-03],
        [2.8120e-02],
        [4.5694e-05],
        [9.9571e-01],
        [7.5218e-03],
        [9.9997e-01],
        [2.0228e-01],
        [1.0000e+00],
        [1.0000e+00],
        [9.5292e-01],
        [7.7449e-01],
        [1.2819e-01],
        [1.7915e-04],
        [1.0000e+00],
        [9.9982e-01],
        [6.1116e-03],
        [3.3877e-05],
        [9.9438e-01],
        [9.9910e-01],
        [3.1335e-02],
        [9.3523e-02],
        [1.1399e-03],
        [1.8869e-03],
        [9.9706e-01],
        [3.6537e-04],
        [4.0370e-06],
        [2.4544e-02],
        [1.0000e+00],
        [4.2651e-04],
        [1.0479e-01],
        [1.5713e-03],
        [9.9744e-01]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [142]:
y_pred_test.shape

torch.Size([114, 1])

In [147]:
y_pred_class = (y_pred_test >= 0.5).double()
y_pred_class

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.]], dtype=torch.float64)

In [148]:
accuracy_score(
    y_test_ten.detach().numpy(),
    y_pred_class.detach().numpy()
)

0.9824561403508771